spring:
  # 1. 应用名称（你已配置）
  application:
    name: qingyun

  # 2. 数据源配置（连接你的MySQL数据库，核心！）
  datasource:
    url: jdbc:mysql://localhost:3306/qingyun?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: qazd924525
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: qingyun_platform_2026_secret_key_123456
  expire: 86400000

logging:
  level:
    com.jycz.qingyun: debug
server:
  port: 8080
